# CI/CD configuration file

# Define stages for the pipeline
stages:
  - build
  - deploy

# Cache configuration to speed up the build process
# cache:
#   key: "$CI_COMMIT_REF_SLUG"
#   paths:
#    - dist/  # Cache the 'build' directory

# Build stage
app_build:
  stage: build
  script:
    - curl -fsSL https://deb.nodesource.com/setup_22.x | bash -  # Configura el repositorio de Node.js
    - apt-get install -y nodejs  # Instala Node.js y npm
    - npm install  # Install project dependencies
    - npm run build  # Build the project
    - echo "Build Completed!"  # Print a completion message
  tags: # Tags specify the GitLab runner where this pipeline will be executed
    - travellirunner
  only: # Define which branches trigger this pipeline stage
    - dev

# Deploy stage
app_deploy:
  stage: deploy
  script:
    - |
      # Change the Key Permissions
      echo "$EC2_KEY" > ec2_key.pem
      
      cat ec2_key.pem

      chmod 600 ec2_key.pem
      
      # Zip the build directory
      zip -r dist.zip dist/

      # Transfer the zip file via SCP
      scp -v -o StrictHostKeyChecking=no -i ec2_key.pem dist.zip $EC2_USERNAME@$EC2_HOST:/var/www/html

      # SSH into the remote server and unzip the file
      ssh -o StrictHostKeyChecking=no -i ec2_key.pem $EC2_USERNAME@$EC2_HOST "rm -vrf /var/www/html/travelli-web/* && cd /var/www/html/travelli-web && mv /var/www/html/dist.zip . && unzip -o dist.zip && mv dist/* ."

      # Remove the zip file after transfer
      rm dist.zip

      echo "Deployment Completed!"  # Print a completion message
  tags:  # Tags specify the GitLab runner where this pipeline will be executed
    - travellirunner
  only:  # Define which branches trigger this pipeline stage
    - dev