# CI/CD configuration file

# Define stages for the pipeline
stages:
  - build
  - deploy

# Cache configuration to speed up the build process
# cache:
#   key: "$CI_COMMIT_REF_SLUG"
#   paths:
#    - dist/  # Cache the 'build' directory

# Build stage
app_build:
  stage: build
  script:
    - curl -fsSL https://deb.nodesource.com/setup_22.x | bash -  # Configura el repositorio de Node.js
    - sudo apt-get install -y nodejs  # Instala Node.js y NPM
    - sudo apt-get install -y zip unzip
    - npm install  # Install project dependencies
    - npm run build  # Build the project
    - ls -la  # Mostrar todos los archivos y carpetas para depuración
    - echo "Build Completed!"  # Print a completion message
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour
  tags: # Tags specify the GitLab runner where this pipeline will be executed
    - travellirunner
  only: # Define which branches trigger this pipeline stage
    - dev

# Deploy stage
app_deploy:
  stage: deploy
  script:
    - |
      # Install zip for compress build folder
      sudo apt update -y && sudo apt-get install -y zip unzip

      # Create .pem file from env variable
      echo "$PUB_KEY" > ec2_key.pem

      # Restrict permissions to .pem file
      chmod 600 ec2_key.pem
      
      # Zip the build directory
      zip -r dist.zip dist/

      # Transfer the zip file via SCP
      scp -v -o StrictHostKeyChecking=no -i ec2_key.pem dist.zip ubuntu@ec2-35-173-56-243.compute-1.amazonaws.com:/tmp

      # SSH into the remote server and unzip the file
      ssh -o StrictHostKeyChecking=no -i ec2_key.pem ubuntu@ec2-35-173-56-243.compute-1.amazonaws.com "sudo rm -rf /var/www/html/travelli-web/* && cd /var/www/html/travelli-web && sudo mv /tmp/dist.zip . && sudo unzip -o dist.zip && sudo rm -rf dist.zip"

      # Remove the zip file after transfer
      sudo rm -rf dist dist.zip

      echo "Deployment Completed!"
  tags:  # Tags specify the GitLab runner where this pipeline will be executed
    - travellirunner
  only:  # Define which branches trigger this pipeline stage
    - dev